<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sora2.Details.Core\Sora2.Details.Core.csproj" />
    <Content Include="..\..\samples\command-battles.json" Link="samples\command-battles.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="assets\skill-icon-map.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.158" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>Sora2.Details.Desktop.Program</StartupObject>
  </PropertyGroup>

</Project>
